services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: zhss
      MYSQL_USERNAME: zhss
      MYSQL_PASSWORD: zhsspy233
    depends_on:
      mysql:
        condition: service_healthy
    container_name: zhss-app

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zhss
      MYSQL_USER: zhss
      MYSQL_PASSWORD: zhsspy233
    volumes:
      - ./mdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: zhss-mysql
